version: "3.4"

services:
  klarna-task-base:
    build:
      context: ./
      target: klarna-task-base
    image: ${DOCKER_REGISTRY}/klarna-task

  rest-api:
    image: ${DOCKER_REGISTRY}/klarna-task
    depends_on:
      - klarna-task-base
    command: python src/server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/home/project

  rest-api-prod:
    build:
      context: ./
      target: klarna-task-prod
    image: ${DOCKER_REGISTRY}/klarna-task-prod

  train-model:
    image: ${DOCKER_REGISTRY}/klarna-task
    depends_on:
      - klarna-task-base
    command: python src/train.py
      --input-csv /home/project/data/dataset.csv
      --output-model /home/project/models/model.joblib
      --output-test-pred /home/project/data/test_predictions.csv
    volumes:
      - .:/home/project

  notebook:
    image: ${DOCKER_REGISTRY}/klarna-task
    depends_on:
      - klarna-task-base
    command: jupyter notebook
      --notebook-dir=/home/project/notebooks
      --ip 0.0.0.0
      --no-browser
      --allow-root
      --port 8899
    ports:
      - "8899:8899"
    volumes:
      - .:/home/project
