version: "3.4"

services:
  rest-api:
    image: 424261332927.dkr.ecr.eu-central-1.amazonaws.com/klarna-task
    depends_on:
      - klarna-task-base
    command: python src/server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/home/project
